### ISSUE TITLE
switch문 예제

### ISSUE THREAD

**Issue by SONGJINSE2** [JS-EatEnjoy-SESAC4/ModernJS_DeepDive_Study#15]
* 다음 switch 문의 출력 결과를 쓰시오.

var i = 1;
var k = 1;

switch (i) {
     case 0:
     case 1:
     case 2: k += 4;
     case 3: k -= 4;
     case 4: k += 3;
     case 5: k -= 10;
     default:  k--;
}

console.log(k);

**Comment by GYoungJang** [comment]
break가 없기 때문에 명령문이 계속 실행됩니다

**Comment by SONGJINSE2** [comment]
> break가 없기 때문에 명령문이 계속 실행됩니다 교재 p.98에 관련 내용이 나와 있네요

break문을 사용하지않아서 case1부터 밑으로 default까지 계산되어 정답은 -7 이 나오게됩니다. 정보처리기사 문제중에 비슷한 문제가 있길래 응용해봤습니다!
