### ISSUE TITLE
빈배열 [] 은 왜 true인가

### ISSUE THREAD

**Issue by Mokdasoo** [JS-EatEnjoy-SESAC4/ModernJS_DeepDive_Study#17]
[] 은 숫자 타입으로 암묵적 타입 변환될 때는 0이 나오는데
불리언 타입으로 암묵적 타입 변환될 때 왜 true가 나오나요

예시코드
function isTruthy(v){
    return !!v;
}
console.log(isTruthy([]));// 불리언 타입 압묵적 타입변환
console.log(+[]);// 숫자 타입 암묵적 타입 변환

**Comment by Mokdasoo** [comment]
+ 
Boolean([]) -> why true?

**Comment by GYoungJang** [comment]
일단 빈 배열 자체가 false 값이 아닌 true 값이어서
if문의 조건으로 빈 배열을 줘도 명령문을 실행합니다
그래서 Boolean([]) 이것도 true 라고 나오는 것 같아요..
왜 +[]이 0인지는 모르겠네요...ㅠ 빈 배열의 length 값이 0이어서 그런가..

**Comment by SONGJINSE2** [comment]
그러네요.. 
빈 문자열은 대입해보면
+' ' => 0 
Boolean(' ') => false가 뜨는데

빈 배열은 
+[ ] => 0
Boolean([ ]) => true가 뜨네요...

하다보니 중괄호도 궁금하네요
+{ } => NaN 인데
Boolean({ }) => true가 뜨네요 이것도 아시는 분 있으면 알려주세요 ㅠㅠ
